name: Publish Python 🐍 distributions 📦 to PyPI

on:
  push:
    branches:
      - main

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install pip
      run: python -m pip install --upgrade pip

    - name: Install wheel
      run: pip install wheel

    - name: Install bump2version
      run: pip install --upgrade bumpversion

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install wheel

    - name: Bump version and commit
      run: |
        git config --local user.email "${{ secrets.USER_EMAIL }}"
        git config --local user.name "Ilies Benhabbour"
        bumpversion patch
        git commit -a -m "Bump version"
        
    - name: Push changes
      run: |
        git fetch origin dev
        git rebase origin/dev
        git push origin HEAD:dev

    - name: Build a binary wheel and a source tarball
      run: python setup.py sdist bdist_wheel

    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
